// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjIMq7xzQ0hUjxY34kjeTHzem-Fs7_4vA',
    appId: '1:141873008523:web:db8d701ad85bcd3d51698e',
    messagingSenderId: '141873008523',
    projectId: 'cityfix-8aa25',
    authDomain: 'cityfix-8aa25.firebaseapp.com',
    storageBucket: 'cityfix-8aa25.firebasestorage.app',
    measurementId: 'G-Q4N5WXDN13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxq0YMBZc17pW2bxNAIw-Trd5xRq8gHCE',
    appId: '1:141873008523:android:33fb28837cff7d0c51698e',
    messagingSenderId: '141873008523',
    projectId: 'cityfix-8aa25',
    storageBucket: 'cityfix-8aa25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzQO6HKcObApfXt88-aaqDjLpdygr3uL4',
    appId: '1:141873008523:ios:45715b6f468359f151698e',
    messagingSenderId: '141873008523',
    projectId: 'cityfix-8aa25',
    storageBucket: 'cityfix-8aa25.firebasestorage.app',
    iosBundleId: 'my.edu.tarc.cityfix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzQO6HKcObApfXt88-aaqDjLpdygr3uL4',
    appId: '1:141873008523:ios:45715b6f468359f151698e',
    messagingSenderId: '141873008523',
    projectId: 'cityfix-8aa25',
    storageBucket: 'cityfix-8aa25.firebasestorage.app',
    iosBundleId: 'my.edu.tarc.cityfix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjIMq7xzQ0hUjxY34kjeTHzem-Fs7_4vA',
    appId: '1:141873008523:web:51aad6230c18965251698e',
    messagingSenderId: '141873008523',
    projectId: 'cityfix-8aa25',
    authDomain: 'cityfix-8aa25.firebaseapp.com',
    storageBucket: 'cityfix-8aa25.firebasestorage.app',
    measurementId: 'G-F7YDYRQP75',
  );
}
